---
- name: Download Node Exporter
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter"


- name: Extract Node Exporter tar.gz
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter"
    dest: "/tmp"
    remote_src: yes

- name: Add the user node_exporter
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    system: true
    create_home: false


- name: Move Node Exporter binaries
  ansible.builtin.copy:
    src: "/tmp/node_exporter-1.6.1.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    remote_src: yes


- name: Create Node Exporter service
  ansible.builtin.template:
    src: "node_exporter.service.j2"
    dest: "/etc/systemd/system/node_exporter.service"


- name: Start and enable Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: started


- name: Update file prometheus.yml
  ansible.builtin.blockinfile:
    path: /etc/prometheus/prometheus.yml
    block: |
      - job_name: 'node_export'
          static_configs:
            - targets: ["localhost:9100"]

- name: Fix indentation
  ansible.builtin.replace:
    path: /etc/prometheus/prometheus.yml
    regexp: "^(- job_name: 'node_export')"
    replace: '  \1'