- name: Install required packages
  ansible.builtin.apt:
    name: 
      - apt-transport-https
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Grafana Apt key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present


- name: Add Grafana repository 
  ansible.builtin.apt_repository: 
    repo: "deb https://packages.grafana.com/oss/deb stable main" 
    state: present

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: yes

- name: Start service Grafana
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- name: Template a file to /etc/grafana/provisioning/datasources
  ansible.builtin.template:
    src: "datasources.yaml.j2"
    dest: /etc/grafana/provisioning/datasources/datasources.yaml
    mode: '0644'

- name: Restart Grafana service
  ansible.builtin.service:
    name: grafana-server
    state: restarted